apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: deployment-demo
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - nodePort: 30500
      port: 80
      protocol: TCP
      targetPort: 80

